# Generated by Django 5.2.1 on 2025-05-19 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Hot Coffee', 'Drinks'), ('Cold COffee', 'drinks'), ('Tea', 'dRinks'), ('DES', 'Dessert')], default='OTHER', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
